name: Build, Push, and Deploy

on:
  push:
    branches:
      - main
    paths:
      - "app/**"

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    outputs:
      image_tag: ${{ steps.set_tag.outputs.tag }}

    steps:
      - name: سحب الكود من الريبو
        uses: actions/checkout@v4

      - name: تحديد رقم النسخة
        id: set_tag
        run: echo "tag=${{ github.run_number }}" >> "$GITHUB_OUTPUT"

      - name: تسجيل الدخول على Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: تجهيز Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: بناء ورفع الصورة
        uses: docker/build-push-action@v5
        with:
          context: ./app
          file: ./app/Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/todo-app:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/todo-app:${{ github.run_number }}

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest

    steps:
      - name: إعداد بيانات AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: تحديث السيرفرات على AWS (Instance Refresh)
        run: |
          aws autoscaling start-instance-refresh \
            --auto-scaling-group-name self-healing-app-asg \
            --preferences '{"MinHealthyPercentage": 50, "InstanceWarmup": 60}'

      - name: طباعة رسالة تأكيد
        run: |
          echo "تم بدء تحديث السيرفرات تلقائيًا على AWS بصورة جديدة."
